#!/bin/bash
clear

DICT_BASEDIR=/Users/bl4de/hacking/dictionaries
LOWERCASE=$DICT_BASEDIR/lowercase.txt
STARTER=$DICT_BASEDIR/starter.txt

url=$1      # base url to fuzz, e.g. http://company.com
ext=$2      # extension e.g. php, asp rb etc. (no dot)
skip=$3     # w!=[NUMBER] for --filter to skip false positives 200 OK

$filter='--filter "c=200"'

if [ -n $skip ]; then
    $filter="--filter \"c=200 and w!=$skip\""
fi

echo -e "\n[+] wfuzz runner | fuzzing $1...:\n"

wfuzz -c $filter "c=200" -w $STARTER $url/FUZZ
wfuzz -c $filter "c=200" -w $LOWERCASE $url/FUZZ/

if [ -n $ext ]; then
   wfuzz -c --filter "c=200" -w $LOWERCASE $url/FUZZ.$ext 
fi

echo -e "\n\n[+] DONE\n"
exit

