#!/bin/bash
# Reverse hostname lookup with nslookup
#
ip=$1
start=$2
end=$3

echo -e "\nusage: ./reverse-lookup 10.10.10 1 10\n"

echo "[+] starting DNS reverse lookup..."
if [[ -z $ip ]]; then
    echo "enter IP e.g. 10.10.10"
    exit 0
fi

# TODO: IP adres wyswietlanie w prawidlowym formacie
for ((i = start; i<end; i++ )); do
    found_host=$(nslookup -type=PTR "$ip.$i" | grep "name =")
    if [[ -n $found_host ]]; then
        echo "$found_host"
    fi
done

echo "[+] done"